name: Deploy Frontend

on:
  push:
    branches:
      - staging
      - prod
      - master

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            
            # Now your npm and pm2 will work
            mkdir -p apps/frontend && cd apps/frontend
            
            mkdir -p apps/frontend && cd apps/frontend
            
            if [ -d ".git" ]; then
              git stash
              git pull origin prod
            else
              git clone -b prod https://github.com/pug-bugger/my-church-cafe.git .
            fi
            
            npm install --force
            npm run build

            pid=$(pm2 pid "church-cafe-front-app" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading application"
              pm2 reload "church-cafe-front-app"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "church-cafe-front-app" -- start
              pm2 startup
              pm2 save
            fi
